# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-18 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marque',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marque',
            name='reduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
