# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='types',
            field=models.ManyToManyField(to='blog.Type'),
        ),
    ]
