# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='contenu',
            field=models.CharField(default=1, max_length=380),
            preserve_default=False,
        ),
    ]
