# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171128_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
